# Generated by Django 2.1.5 on 2020-05-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20200515_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sex_for',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('UNISEX', 'UNISEX')], max_length=225, null=True),
        ),
    ]
