# Generated by Django 2.1.5 on 2020-05-15 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200515_1115'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='prodImage',
        ),
    ]
