# Generated by Django 2.1.5 on 2020-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_auto_20200515_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='imageF',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='imageS',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='imageT',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
